// app/layout.tsx

// Agar global css ya fonts hain to import
import "./globals.css";
import type { Metadata } from "next";

// Optional: metadata export if aap use karte ho
export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
